language: go

go:
  - '1.10'
  - '1.11'
  - '1.12'
  - '1.13'
  - '1.14'
env:
  - GO111MODULE=auto
before_install:
  - go get -v golang.org/x/net/html
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -v ./